apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: mvp-alerts
spec:
  groups:
  - name: mvp.rules
    rules:
    - alert: HighRequestLatency
      expr: histogram_quantile(0.95, sum(rate(http_request_latency_seconds_bucket[5m])) by (le, endpoint)) > 1
      for: 2m
      labels:
        severity: warning
      annotations:
        summary: "High request latency (p95 > 1s)"
    - alert: HighErrorRate
      expr: sum(rate(http_requests_total{http_status=~"5.."}[5m])) by (endpoint) > 0.1
      for: 2m
      labels:
        severity: critical
      annotations:
        summary: "High 5xx error rate"
