apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mvp-servicemonitor
spec:
  selector:
    matchLabels:
      app: mvp-app
  endpoints:
  - port: web
    path: /metrics
    interval: 15s
