name: Main

on:
  workflow_dispatch:
  # push:
  #   branches: [ main ]

jobs:
  build:
    uses: ./.github/workflows/build.yml

  deploy:
    needs: build
    uses: ./.github/workflows/deploy.yml

  test:
    needs: deploy
    uses: ./.github/workflows/test.yml


