name: Test

on:
  workflow_dispatch:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    # --------------------
    # API tests (pytest)
    # --------------------
    - name: Run API tests (pytest)
      run: |
        pip install -r app/requirements.txt
        pip install pytest requests
        pytest qa/api_tests/test_api.py --junitxml=api-report.xml
      continue-on-error: false

    - name: Publish API results
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: API Tests
        path: api-report.xml
        reporter: java-junit

    - name: Upload API report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: api-report
        path: api-report.xml

    # --------------------
    # Playwright tests
    # --------------------
    - name: Install Playwright dependencies
      run: |
        cd qa/ui_tests/playwright
        npm install
        npx playwright install --with-deps

    - name: Run Playwright UI tests
      run: |
        cd qa/ui_tests/playwright
        BASE_URL="http://18.196.175.161:8080" npx playwright test \
          --reporter=dot,junit=playwright-report.xml \
          --output=test-results

    - name: Publish Playwright results
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: UI Tests
        path: qa/ui_tests/playwright/playwright-report.xml
        reporter: java-junit

    - name: Upload Playwright report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: qa/ui_tests/playwright/playwright-report.xml
